# Generated by Django 3.0.4 on 2020-03-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='Country',
        ),
    ]
