# Generated by Django 3.0.4 on 2020-03-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20200310_0559'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='state',
            table='State',
        ),
    ]
