# Generated by Django 3.0.4 on 2020-03-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_auto_20200310_0600'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table=None,
        ),
        migrations.AlterModelTable(
            name='state',
            table=None,
        ),
    ]
