# Generated by Django 3.0.4 on 2020-03-10 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_auto_20200310_0658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, default='', max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.State')),
            ],
        ),
    ]
