# Generated by Django 3.0.4 on 2020-03-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_auto_20200310_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
